In [1]:
import numpy as np
vec1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
vec1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
mat2 = np.matrix([[1, 2, 3], [4, 5, 6], \
                  [7, 8, 9], [10, 11, 12]])

In [4]:
ten1 = np.array([[[1, 2, 3], [4, 5, 6]], \
                 [[7, 8, 9], [10, 11, 12]]])
ten1


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
vec1.shape

(10,)

In [6]:
mat1.shape

(4, 3)

In [7]:
ten1.shape

(2, 2, 3)

In [8]:
mat1 = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
mat1

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [9]:
mat2 = np.matrix([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
mat2

matrix([[ 2,  1,  4],
        [ 4,  1,  7],
        [ 4,  2,  9],
        [ 5, 21,  1]])

In [10]:
mat3 = mat1 + mat2
mat3

matrix([[ 3,  3,  7],
        [ 8,  6, 13],
        [11, 10, 18],
        [15, 32, 13]])

In [11]:
mat1 + 4

matrix([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13],
        [14, 15, 16]])